config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  devise_for :users, path_names:  { sign_in: "login", sign_out: "logout" },
                     controllers: {
                                    registrations: "user/registrations"
                                  }


  #===============Api Routes================
  require 'api_constraints'

   namespace :api, defaults: { format: :json } do
       # scope per version of api
       scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

         resources :sessions, :only      => [:create, :destroy]
         match '/login'                  => 'sessions#create', :via => [:options, :post]
         post '/logout/:user_id'         => 'sessions#destroy'

         match '/reset_password'         => 'users#reset_password', :via => [:post]
         match '/users/:id'              => 'users#update', :via => [:options, :put, :post]
        #  get '/matches'                  => 'matches#show'

         resources :users, :only         => [:show, :create, :update]

         resources :dealerships, :only   => [:index, :show] do
           resources :sales_reps, :controller => 'sales_reps', :only => [:index, :show]
           resources :service_reps, :controller => 'service_reps', :only => [:index, :show]
         end

         resources :messages

         resources :conversations do
          resources :messages
         end
     end
   end
   #==========================================

  resources :users, only: [:index, :show, :destroy]
  resources :moderators, :controller => 'moderators'
  resources :sales_reps, :controller => 'sales_reps'
  resources :service_reps, :controller => 'service_reps'
  # devise_for :users

  resources :dealerships
  resources :push_notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dealership.rb
class Dealership < ApplicationRecord
  resourcify

  has_many :users

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

  has_attached_file :background_image, styles: { medium: "600x600>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
end

app/controllers/api/v1/dealerships_controller.rb
class Api::V1::DealershipsController < Api::ApiController
  # load_and_authorize_resource
  # before_action :authenticate_with_token!

  def index
    @dealerships = Dealership.all.order('name ASC')
  end

  def show
    @dealership = Dealership.find(params[:id])
  end

  private
    # def dealership_params
    #   params.require(:dealership).permit(:id)
    # end
end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  load_and_authorize_resource
  before_action :set_dealership, only: [:show, :edit, :update, :destroy]

  # GET /dealerships
  # GET /dealerships.json
  def index
    @dealerships = Dealership.all
  end

  # GET /dealerships/1
  # GET /dealerships/1.json
  def show
  end

  # GET /dealerships/new
  def new
    @dealership = Dealership.new
  end

  # GET /dealerships/1/edit
  def edit
  end

  # POST /dealerships
  # POST /dealerships.json
  def create
    @dealership = Dealership.new(dealership_params)

    respond_to do |format|
      if @dealership.save
        format.html { redirect_to dealerships_url, notice: 'Dealership was successfully created.' }
        format.json { render :show, status: :created, location: @dealership }
      else
        format.html { render :new }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealerships/1
  # PATCH/PUT /dealerships/1.json
  def update
    respond_to do |format|
      if @dealership.update(dealership_params)
        format.html { redirect_to dealerships_url, notice: 'Your Dealership was successfully updated.' }
        format.json { render :show, status: :ok, location: @dealership }
      else
        format.html { render :edit }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealerships/1
  # DELETE /dealerships/1.json
  def destroy
    @dealership.destroy
    respond_to do |format|
      format.html { redirect_to dealerships_url, notice: 'Dealership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealership
      @dealership = Dealership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dealership_params
      params.fetch(:dealership, {}).permit(:name, :phone, :primary_color, :new_cars_url, :used_cars_url, :service_url, :specials_url, :service_specials_url, :parts_url, :financing_url, :sales_email, :service_email, :street, :city, :state, :country, :zipcode, :logo, :background_image, :iframeFriendly, :facebook_url, :twitter_url)
    end
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/views/dealerships/_form.html.erb
<!-- Im fairly certain this is not being used at all -->



<div class="container">
  <%= form_for(dealership) do |f| %>
    <% if dealership.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(dealership.errors.count, "error") %> prohibited this dealership from being saved:</h2>

        <ul>
        <% dealership.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <!-- <div style="border: 0.1rem solid gray; border-radius: 1rem;padding: 2rem;"> -->
    <div class="form-group row">
      <label for="inputName" class="col-sm-2 col-form-label">Name</label>
      <div class="col-sm-10">
        <%= f.text_field :name, :id=> "inputName", :class=> "form-control", :placeholder=>"Name", autofocus: true %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputPhone" class="col-sm-2 col-form-label">Phone</label>
      <div class="col-sm-10">
        <%= f.telephone_field :phone, :id=> "inputPhone", :class=> "form-control", :placeholder=>"Phone"%>
      </div>
    </div>
    <!-- </div> -->
    <div class="form-group row">
      <label for="inputPrimaryColor" class="col-sm-2 col-form-label">Primary Color</label>
      <div class="col-sm-10">
        <%= f.color_field :primary_color, :id=> "inputPrimaryColor", :class=> "form-control" %>
      </div>
    </div>

    <hr />

    <div class="form-group row">
      <label for="inputLogo" class="col-sm-2 col-form-label">Logo</label>
      <div class="col-sm-10">
        <%= f.file_field :logo, :id=> "inputLogo", :class=> "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputBackgroundImage" class="col-sm-2 col-form-label">Background Image</label>
      <div class="col-sm-10">
        <%= f.file_field :background_image, :id=> "inputBackgroundImage", :class=> "form-control" %>
      </div>
    </div>

    <hr />

    <div class="form-group row">
      <label for="inputNewCarsUrl" class="col-sm-2 col-form-label">New Cars Url</label>
      <div class="col-sm-10">
        <%= f.url_field :new_cars_url, :id=> "inputNewCarsUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/new_cars" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputUsedCarsUrl" class="col-sm-2 col-form-label">Used Cars Url</label>
      <div class="col-sm-10">
        <%= f.url_field :used_cars_url, :id=> "inputUsedCarsUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/used_cars"  %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputServiceUrl" class="col-sm-2 col-form-label">Service Url</label>
      <div class="col-sm-10">
        <%= f.url_field :service_url, :id=> "inputServiceUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/service"  %>
      </div>
    </div>

    <hr />

    <div class="form-group row">
      <label for="inputSalesEmail" class="col-sm-2 col-form-label">Sales Email</label>
      <div class="col-sm-10">
        <%= f.email_field :sales_email, :id=> "inputSalesEmail", :class=> "form-control", :placeholder=>"sales@dealership.com" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputServiceEmail" class="col-sm-2 col-form-label">Service Email</label>
      <div class="col-sm-10">
        <%= f.email_field :service_email, :id=> "inputServiceEmail", :class=> "form-control", :placeholder=>"service@dealership.com" %>
      </div>
    </div>

    <hr />

    <div class="form-group row">
      <label for="inputStreet" class="col-sm-2 col-form-label">Street</label>
      <div class="col-sm-10">
        <%= f.text_field :street, :id=> "inputStreet", :class=> "form-control", :placeholder=>"1111 Example Ave." %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputCity" class="col-sm-2 col-form-label">City</label>
      <div class="col-sm-10">
        <%= f.text_field :city, :id=> "inputCity", :class=> "form-control", :placeholder=>"Charleston" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputState" class="col-sm-2 col-form-label">State</label>
      <div class="col-sm-10">
        <%= f.text_field :state, :id=> "inputState", :class=> "form-control", :placeholder=>"South Carolina" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputZipcode" class="col-sm-2 col-form-label">Zipcode</label>
      <div class="col-sm-10">
        <%= f.text_field :zipcode, :id=> "inputZipcode", :class=> "form-control", :placeholder=>"29403" %>
      </div>
    </div>


    <div class="form-group row">
      <div class="offset-sm-2 col-sm-10">
        <!-- <button type="submit" class="btn btn-primary">Add</button> -->
        <%= f.submit "Add", :type => "submit", :class=>"btn btn-primary" %>
        <%= f.submit "Clear", :type => "reset", :class=>"btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/dealerships/edit.html.erb
<div class="col-lg-10 offset-lg-1">
  <div class="row">
    <h1 class="text-sm-center">Edit Dealership</h1>
  </div>

  <div class="container" style="padding-top:2em">
    <%= form_for(@dealership) do |f| %>
      <% if @dealership.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(dealership.errors.count, "error") %> prohibited this dealership from being saved:</h2>

          <ul>
          <% @dealership.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <!-- <div style="border: 0.1rem solid gray; border-radius: 1rem;padding: 2rem;"> -->
      <div class="form-group row">
        <label for="inputName" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
          <%= f.text_field :name, :id=> "inputName", :class=> "form-control", :placeholder=>"Name", autofocus: true %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputPhone" class="col-sm-2 col-form-label">Phone</label>
        <div class="col-sm-10">
          <%= f.telephone_field :phone, :id=> "inputPhone", :class=> "form-control", :placeholder=>"Phone"%>
        </div>
      </div>
      <!-- </div> -->
      <div class="form-group row">
        <label for="inputPrimaryColor" class="col-sm-2 col-form-label">Primary Color</label>
        <div class="col-sm-10">
          <%= f.color_field :primary_color, :id=> "inputPrimaryColor", :class=> "form-control" %>
        </div>
      </div>

      <hr />

      <div class="form-group row">
        <label for="inputLogo" class="col-sm-2 col-form-label">Logo</label>
        <div class="col-sm-5">
          <%= f.file_field :logo, :id=> "inputLogo", :class=> "form-control" %>
        </div>
        <div class="col-sm-5 text-sm-center">
          <%= image_tag @dealership.logo.url(:thumb) %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputBackgroundImage" class="col-sm-2 col-form-label">Background Image</label>
        <div class="col-sm-5">
          <%= f.file_field :background_image, :id=> "inputBackgroundImage", :class=> "form-control" %>
        </div>
        <div class="col-sm-5 text-sm-center">
          <%= image_tag @dealership.background_image.url(:medium), :style=>"width:50%;" %>
        </div>
      </div>

      <hr />

      <div class="form-group row">
        <label for="inputNewCarsUrl" class="col-sm-2 col-form-label">New Sales Url</label>
        <div class="col-sm-10">
          <%= f.url_field :new_cars_url, :id=> "inputNewCarsUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/new_cars" %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputUsedCarsUrl" class="col-sm-2 col-form-label">Used Sales Url</label>
        <div class="col-sm-10">
          <%= f.url_field :used_cars_url, :id=> "inputUsedCarsUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/used_cars"  %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputServiceUrl" class="col-sm-2 col-form-label">Service Url</label>
        <div class="col-sm-10">
          <%= f.url_field :service_url, :id=> "inputServiceUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/service"  %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputSpecialsUrl" class="col-sm-2 col-form-label">Specials Url</label>
        <div class="col-sm-10">
          <%= f.url_field :specials_url, :id=> "inputSpecialsUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/specials"  %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputServSpecialsUrl" class="col-sm-2 col-form-label">Service Specials Url</label>
        <div class="col-sm-10">
          <%= f.url_field :service_specials_url, :id=> "inputServSpecialsUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/specials"  %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputPartsUrl" class="col-sm-2 col-form-label">Parts Url</label>
        <div class="col-sm-10">
          <%= f.url_field :parts_url, :id=> "inputPartsUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/parts"  %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputFinancingUrl" class="col-sm-2 col-form-label">Financing Url</label>
        <div class="col-sm-10">
          <%= f.url_field :financing_url, :id=> "inputFinancingUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/financing"  %>
        </div>
      </div>

      <hr />

      <div class="form-group row">
        <label for="inputSalesEmail" class="col-sm-2 col-form-label">Sales Email</label>
        <div class="col-sm-10">
          <%= f.email_field :sales_email, :id=> "inputSalesEmail", :class=> "form-control", :placeholder=>"sales@dealership.com" %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputServiceEmail" class="col-sm-2 col-form-label">Service Email</label>
        <div class="col-sm-10">
          <%= f.email_field :service_email, :id=> "inputServiceEmail", :class=> "form-control", :placeholder=>"service@dealership.com" %>
        </div>
      </div>

      <hr />

      <div class="form-group row">
        <label for="inputTwitter" class="col-sm-2 col-form-label">Twitter Url</label>
        <div class="col-sm-10">
          <%= f.url_field :twitter_url, :id=> "inputTwitter", :class=> "form-control", :placeholder=>"https://twitter.com/bakermotorcochs" %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputFacebook" class="col-sm-2 col-form-label">Facebook Url</label>
        <div class="col-sm-10">
          <%= f.url_field :facebook_url, :id=> "inputFacebook", :class=> "form-control", :placeholder=>"https://www.facebook.com/dealershipName" %>
        </div>
      </div>

      <hr />

      <div class="form-group row">
        <label for="inputStreet" class="col-sm-2 col-form-label">Street</label>
        <div class="col-sm-10">
          <%= f.text_field :street, :id=> "inputStreet", :class=> "form-control", :placeholder=>"1111 Example Ave." %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputCity" class="col-sm-2 col-form-label">City</label>
        <div class="col-sm-10">
          <%= f.text_field :city, :id=> "inputCity", :class=> "form-control", :placeholder=>"Charleston" %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputState" class="col-sm-2 col-form-label">State</label>
        <div class="col-sm-10">
          <%= f.text_field :state, :id=> "inputState", :class=> "form-control", :placeholder=>"South Carolina" %>
        </div>
      </div>

      <div class="form-group row">
        <label for="inputZipcode" class="col-sm-2 col-form-label">Zipcode</label>
        <div class="col-sm-10">
          <%= f.text_field :zipcode, :id=> "inputZipcode", :class=> "form-control", :placeholder=>"29403" %>
        </div>
      </div>

      <hr />
      <div class="form-group row">
        <label class="col-sm-2">iframe Friendly</label>
        <div class="col-sm-10">
          <%= f.check_box :iframeFriendly, :class=> "form-check-input" %>
          <%= f.label :iframeFriendly, "Are your links iframe friendly?" %>
        </div>
      </div>


      <div class="form-group row">
        <div class="offset-sm-2 col-sm-10">
          <!-- <button type="submit" class="btn btn-primary">Add</button> -->
          <%= f.submit "Edit", :type => "submit", :class=>"btn btn-primary" %>
          <%= link_to 'Back', dealerships_path, :class=>"btn btn-info" %>
        </div>
      </div>
    <% end %>
  </div>


<!-- <%= link_to 'Show', @dealership %> |
<%= link_to 'Back', dealerships_path %>
</div> -->

app/views/dealerships/index.html.erb
<div class="col-lg-10 offset-lg-1">

<h1 class="text-md-center">Dealerships</h1>


  <div class="row">
    <% if current_user.has_role? :admin %>
    <div class="pull-right">
      <%= link_to 'Add New Dealership', new_dealership_path, :class=>"btn btn-info"  %>
    </div>
    <% end %>
    <div class="text-lg-left">
      <%= link_to root_path, :class=>"btn btn-danger" do  %>
        <i class="fa fa-chevron-circle-left fa-fw" aria-hidden="true"></i>Back
      <% end %>
    </div>
  </div>



<div class="row" style="padding: 2rem 0">
  <table class="table table-hover" style="background-color: white; padding-top:5rem; border-left: 1px solid #ddd; border-right: 1px solid #ddd; border-bottom: 1px solid #ddd; border-radius: 0rem 0rem .25rem .25rem">
    <thead>
      <tr>
        <th>
          Logo
        </th>
        <th>Name</th>
        <th colspan="1" class="text-center"></th>
        <!-- <th colspan="3"></th> -->
      </tr>
    </thead>

    <tbody>
      <% @dealerships.each do |dealership| %>
        <tr data-href='<%= dealership_path(dealership.id)%>'>
          <td><%= image_tag dealership.logo.url(:thumb) %></td>
          <td><%= dealership.name %></td>
          <td class="text-lg-right">
            <!-- <%= link_to 'Show', dealership, :class=>"btn btn-outline-primary" if can? :read, dealership %> -->
            <%= link_to 'Edit', edit_dealership_path(dealership), :class=>"btn btn-outline-warning btn-sm" if can? :update, dealership %>
            <%= link_to 'Remove', dealership, :class=>"btn btn-outline-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } if can? :manage, dealership %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>

</div>



<!-- <script>
jQuery(document).ready(function($) {
    $('.table > tbody > tr').click(function() {
        window.document.location = $(this).data("href");
    });
});
</script> -->

app/views/dealerships/new.html.erb
<h1 class="text-xs-center">Add Dealership</h1>

<div class="container">
  <%= form_for(@dealership) do |f| %>
    <% if @dealership.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@dealership.errors.count, "error") %> prohibited this dealership from being saved:</h2>

        <ul>
        <% @dealership.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <!-- <div style="border: 0.1rem solid gray; border-radius: 1rem;padding: 2rem;"> -->
    <div class="form-group row">
      <label for="inputName" class="col-sm-2 col-form-label">Name</label>
      <div class="col-sm-10">
        <%= f.text_field :name, :id=> "inputName", :class=> "form-control", :placeholder=>"Name", autofocus: true %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputPhone" class="col-sm-2 col-form-label">Phone</label>
      <div class="col-sm-10">
        <%= f.telephone_field :phone, :id=> "inputPhone", :class=> "form-control", :placeholder=>"Phone"%>
      </div>
    </div>
    <!-- </div> -->
    <div class="form-group row">
      <label for="inputPrimaryColor" class="col-sm-2 col-form-label">Primary Color</label>
      <div class="col-sm-10">
        <%= f.color_field :primary_color, :id=> "inputPrimaryColor", :class=> "form-control" %>
      </div>
    </div>

    <hr />

    <div class="form-group row">
      <label for="inputLogo" class="col-sm-2 col-form-label">Logo</label>
      <div class="col-sm-10">
        <%= f.file_field :logo, :id=> "inputLogo", :class=> "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputBackgroundImage" class="col-sm-2 col-form-label">Background Image</label>
      <div class="col-sm-10">
        <%= f.file_field :background_image, :id=> "inputBackgroundImage", :class=> "form-control" %>
      </div>
    </div>

    <hr />

    <div class="form-group row">
      <label for="inputNewCarsUrl" class="col-sm-2 col-form-label">New Sales Url</label>
      <div class="col-sm-10">
        <%= f.url_field :new_cars_url, :id=> "inputNewCarsUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/new_cars" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputUsedCarsUrl" class="col-sm-2 col-form-label">Used Sales Url</label>
      <div class="col-sm-10">
        <%= f.url_field :used_cars_url, :id=> "inputUsedCarsUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/used_cars"  %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputServiceUrl" class="col-sm-2 col-form-label">Service Url</label>
      <div class="col-sm-10">
        <%= f.url_field :service_url, :id=> "inputServiceUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/service"  %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputServiceUrl" class="col-sm-2 col-form-label">Specials Url</label>
      <div class="col-sm-10">
        <%= f.url_field :specials_url, :id=> "inputServiceUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/specials"  %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputServSpecialsUrl" class="col-sm-2 col-form-label">Service Specials Url</label>
      <div class="col-sm-10">
        <%= f.url_field :service_specials_url, :id=> "inputServSpecialsUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/specials"  %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputPartsUrl" class="col-sm-2 col-form-label">Parts Url</label>
      <div class="col-sm-10">
        <%= f.url_field :parts_url, :id=> "inputPartsUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/parts"  %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputFinancingUrl" class="col-sm-2 col-form-label">Financing Url</label>
      <div class="col-sm-10">
        <%= f.url_field :financing_url, :id=> "inputFinancingUrl", :class=> "form-control", :placeholder=>"http://www.dealership.com/financing"  %>
      </div>
    </div>

    <hr />

    <div class="form-group row">
      <label for="inputSalesEmail" class="col-sm-2 col-form-label">Sales Email</label>
      <div class="col-sm-10">
        <%= f.email_field :sales_email, :id=> "inputSalesEmail", :class=> "form-control", :placeholder=>"sales@dealership.com" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputServiceEmail" class="col-sm-2 col-form-label">Service Email</label>
      <div class="col-sm-10">
        <%= f.email_field :service_email, :id=> "inputServiceEmail", :class=> "form-control", :placeholder=>"service@dealership.com" %>
      </div>
    </div>

    <hr />

    <div class="form-group row">
      <label for="inputTwitter" class="col-sm-2 col-form-label">Twitter Url</label>
      <div class="col-sm-10">
        <%= f.url_field :twitter_url, :id=> "inputTwitter", :class=> "form-control", :placeholder=>"https://twitter.com/bakermotorcochs" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputFacebook" class="col-sm-2 col-form-label">Facebook Url</label>
      <div class="col-sm-10">
        <%= f.url_field :facebook_url, :id=> "inputFacebook", :class=> "form-control", :placeholder=>"https://www.facebook.com/dealershipName" %>
      </div>
    </div>

    <hr />

    <div class="form-group row">
      <label for="inputStreet" class="col-sm-2 col-form-label">Street</label>
      <div class="col-sm-10">
        <%= f.text_field :street, :id=> "inputStreet", :class=> "form-control", :placeholder=>"1111 Example Ave." %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputCity" class="col-sm-2 col-form-label">City</label>
      <div class="col-sm-10">
        <%= f.text_field :city, :id=> "inputCity", :class=> "form-control", :placeholder=>"Charleston" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputState" class="col-sm-2 col-form-label">State</label>
      <div class="col-sm-10">
        <%= f.text_field :state, :id=> "inputState", :class=> "form-control", :placeholder=>"South Carolina" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputZipcode" class="col-sm-2 col-form-label">Zipcode</label>
      <div class="col-sm-10">
        <%= f.text_field :zipcode, :id=> "inputZipcode", :class=> "form-control", :placeholder=>"29403" %>
      </div>
    </div>


    <hr />
    <div class="form-group row">
      <label class="col-sm-2">iframe Friendly</label>
      <div class="col-sm-10">
        <%= f.check_box :iframeFriendly, :class=> "form-check-input" %>
        <%= f.label :iframeFriendly, "Are your links iframe friendly?" %>
      </div>
    </div>



    <div class="form-group row">
      <div class="offset-sm-2 col-sm-10">
        <!-- <button type="submit" class="btn btn-primary">Add</button> -->
        <%= f.submit "Create", :type => "submit", :class=>"btn btn-primary" %>
        <%= link_to 'Back', dealerships_path, :class=>"btn btn-info" %>
      </div>
    </div>
  <% end %>
</div>

app/views/dealerships/show.html.erb
<% if can? :update, @dealership  %>
  <%= link_to 'Edit', edit_dealership_path(@dealership)%> |
<% end %>
<%= link_to 'Back', dealerships_path %>