config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  devise_for :users, path_names:  { sign_in: "login", sign_out: "logout" },
                     controllers: {
                                    registrations: "user/registrations"
                                  }


  #===============Api Routes================
  require 'api_constraints'

   namespace :api, defaults: { format: :json } do
       # scope per version of api
       scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

         resources :sessions, :only      => [:create, :destroy]
         match '/login'                  => 'sessions#create', :via => [:options, :post]
         post '/logout/:user_id'         => 'sessions#destroy'

         match '/reset_password'         => 'users#reset_password', :via => [:post]
         match '/users/:id'              => 'users#update', :via => [:options, :put, :post]
        #  get '/matches'                  => 'matches#show'

         resources :users, :only         => [:show, :create, :update]

         resources :dealerships, :only   => [:index, :show] do
           resources :sales_reps, :controller => 'sales_reps', :only => [:index, :show]
           resources :service_reps, :controller => 'service_reps', :only => [:index, :show]
         end

         resources :messages

         resources :conversations do
          resources :messages
         end
     end
   end
   #==========================================

  resources :users, only: [:index, :show, :destroy]
  resources :moderators, :controller => 'moderators'
  resources :sales_reps, :controller => 'sales_reps'
  resources :service_reps, :controller => 'service_reps'
  # devise_for :users

  resources :dealerships
  resources :push_notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_admin_dashboard.html.erb
<div class="col-lg-10 offset-lg-1">
  <div class="row">
    <h1 class="text-sm-center" style="padding: 1rem 0">Admin Dashboard</h1>
  </div>
  <div class="row text-lg-right">
    <%= link_to "Manage Dealerships", dealerships_path, :class => "btn btn-info" %>
    <%= link_to "Push Notifications", push_notifications_path, :class => "btn btn-warning" %>
  </div>

  <div class="row" style="padding: 2rem 0">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" href="#moderator" role="tab" data-toggle="tab">Moderators</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#sales_rep" role="tab" data-toggle="tab">Sales Reps</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#service_rep" role="tab" data-toggle="tab">Service Reps</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#customer" role="tab" data-toggle="tab">Customers</a>
      </li>

    </ul>

    <!-- Tab panes -->
    <div class="tab-content" style= "background-color: white; border-left: 1px solid #ddd; border-right: 1px solid #ddd; border-bottom: 1px solid #ddd; border-radius: 0rem 0rem .25rem .25rem">
      <div role="tabpanel" class="tab-pane fade in active" id="moderator">
        <table class="table table-hover" style="padding-top:5rem;">
          <thead>
            <tr>
              <th style="border-top:transparent">
                Email
              </th>
              <th style="border-top:transparent">Name</th>
              <th style="border-top:transparent">Dealership</th>
              <th colspan="1" class="text-lg-center" style="border-top:transparent">Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @moderators.each do |moderator| %>
              <tr>
                <td><%= moderator.email %></td>
                <td><%= moderator.name %></td>
                <td><%= Dealership.with_role(:moderator, moderator).first.name %></td>
                <td class="text-lg-center">
                  <!-- <%= link_to 'Edit', edit_registration_path(moderator), :class=>"btn btn-danger" %> -->
                  <%= link_to 'Remove', moderator, :class=>"btn btn-sm btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="row" style="margin: 1rem;border-top: .1rem solid #ddd;padding-top: 1rem;">
          <%= link_to new_moderator_url, :class => "btn btn-info" do %>
            <i class="fa fa-plus-circle" aria-hidden="true"></i> Add Moderator
          <% end %>
        </div>
      </div>
      <!-- END MODERATORS -->
      <!-- BEGIN SALES REP -->
      <div role="tabpanel" class="tab-pane fade" id="sales_rep">
        <table class="table table-hover" style="padding-top:5rem;">
          <thead>
            <tr>
              <th style="border-top:transparent">Image</th>
              <th style="border-top:transparent">Email</th>
              <th style="border-top:transparent">Name</th>
              <th style="border-top:transparent">Dealership</th>
              <th colspan="1" class="text-lg-center" style="border-top:transparent">Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @sales_reps.each do |rep| %>
              <tr>
                <td><%= image_tag rep.image.url(:thumb), style: "max-width:50px" %></td>
                <td><%= rep.email %></td>
                <td><%= rep.name %></td>
                <td><%= Dealership.with_role(:sales_rep, rep).first.name %></td>
                <td class="text-lg-center">
                  <%= link_to 'Edit',  edit_sales_rep_path(rep), :class=>"btn btn-danger" %>
                  <%= link_to 'Remove', rep, :class=>"btn btn-sm btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="row" style="margin: 1rem;border-top: .1rem solid #ddd;padding-top: 1rem;">
          <%= link_to new_sales_rep_url, :class => "btn btn-info" do %>
            <i class="fa fa-plus-circle" aria-hidden="true"></i> Add Sales Representative
          <% end %>
        </div>
      </div>
      <!-- END SALES REP -->
      <!-- BEGIN SERVICE REP -->
      <div role="tabpanel" class="tab-pane fade" id="service_rep">
        <table class="table table-hover" style="padding-top:5rem;">
          <thead>
            <tr>
              <th style="border-top:transparent">Image</th>
              <th style="border-top:transparent">Email</th>
              <th style="border-top:transparent">Name</th>
              <th style="border-top:transparent">Dealership</th>
              <th colspan="1" class="text-lg-center" style="border-top:transparent">Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @service_reps.each do |rep| %>
              <tr>
                <td><%= image_tag rep.image.url(:thumb), style: "max-width:50px"  %></td>
                <td><%= rep.email %></td>
                <td><%= rep.name %></td>
                <td><%= Dealership.with_role(:service_rep, rep).first.name %></td>
                <td class="text-lg-center">
                  <%= link_to 'Edit', edit_service_rep_path(rep), :class=>"btn btn-danger" %>
                  <%= link_to 'Remove', rep, :class=>"btn btn-sm btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="row" style="margin: 1rem;border-top: .1rem solid #ddd;padding-top: 1rem;">
          <%= link_to new_service_rep_url, :class => "btn btn-info" do %>
            <i class="fa fa-plus-circle" aria-hidden="true"></i> Add Service Representative
          <% end %>
        </div>
      </div>
      <!-- END SERVICE REP -->
      <div role="tabpanel" class="tab-pane fade" id="customer">
        <table class="table table-hover" style="padding-top:5rem;">
          <thead>
            <tr>
              <th style="border-top:transparent">
                Email
              </th>
              <th style="border-top:transparent">Name</th>
              <th style="border-top:transparent">Dealership</th>
              <th colspan="1" class="text-lg-center" style="border-top:transparent">Actions</th>
              <!-- <th colspan="3"></th> -->
            </tr>
          </thead>

          <tbody>
            <% @customers.each do |customer| %>
              <tr>
                <td><%= customer.email %></td>
                <td><%= customer.name %></td>
                <td><%= customer.dealership.name if customer.dealership %></td>
                <td class="text-lg-center">
                  <%= link_to 'Remove', customer, :class=>"btn btn-sm btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- <div role="tabpanel" class="tab-pane fade" id="references">ccc</div> -->
    </div>
  </div>
</div>

app/views/partials/_customer_dashboard.html.erb
<div class="row">
<h1 class="text-sm-center">Customer Dashboard</h1>
</div>

app/views/partials/_header.html.erb
<nav class="navbar navbar-dark bg-inverse navbar-fixed-top">
  <%= link_to "Baker Motor Company", root_path, :class => "navbar-brand" %>
  <ul class="nav navbar-nav">
    <!-- <li class="nav-item">
      <%= link_to "My Dealerships", dealerships_path, :class => "nav-link" %>
    </li> -->
    <li class="nav-item pull-md-right">
      <% if user_signed_in? %>
        <%= link_to 'Log out', destroy_user_session_path, :class=>"nav-link", method: :delete%>
      <% else %>
        <%= link_to 'Log In', new_user_session_path, :class=>"nav-link" %>
          <!-- <%= link_to 'Sign Up', new_user_registration_path %> -->
      <% end %>
    </li>
  </ul>
</nav>

app/views/partials/_index.html.erb
<div class="row">
<h1 class="text-sm-center">Standard Landing Page</h1>
<p>
  Place link to app here maybe... def background image
</p>
</div>

app/views/partials/_moderator_dashboard.html.erb
<div class="col-lg-10 offset-lg-1">
<div class="row">
  <h1 class="text-sm-center">Moderator Dashboard</h1>
</div>
<div class="row text-lg-right">
  <%= link_to "Dealership Settings", edit_dealership_path(@dealership), :class => "btn btn-info" %>
  <!-- <%= link_to "Moderators", dealerships_path, :class => "btn btn-outline-success btn-lg" %> -->
  <!-- <%= link_to "Customers", dealerships_path, :class => "btn btn-outline-info btn-lg" %> -->
</div>


<div class="row" style="padding: 2rem 0">
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" href="#customer" role="tab" data-toggle="tab">Customers</a>
    </li>
    <!-- <li class="nav-item">
      <a class="nav-link" href="#customer" role="tab" data-toggle="tab">Customers</a>
    </li> -->
    <!-- <li class="nav-item">
      <a class="nav-link" href="#references" role="tab" data-toggle="tab">references</a>
    </li> -->
  </ul>

  <!-- Tab panes -->
  <div class="tab-content" style= "background-color: white; border-left: 1px solid #ddd; border-right: 1px solid #ddd; border-bottom: 1px solid #ddd; border-radius: 0rem 0rem .25rem .25rem">
    <div role="tabpanel" class="tab-pane fade in active" id="customer">
      <table class="table table-hover" style="padding-top:5rem;">
        <thead>
          <tr>
            <th style="border-top:transparent">
              Email
            </th>
            <th style="border-top:transparent">Name</th>
            <th colspan="1" class="text-lg-center" style="border-top:transparent">Actions</th>
            <!-- <th colspan="3"></th> -->
          </tr>
        </thead>

        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.email %></td>
              <td>
              </td>
              <td class="text-lg-center">
                <%= link_to "Send Message", root_path, :class=>"btn btn-primary" %>
                <!-- <%= link_to 'Destroy', customer, :class=>"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %> -->
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="moderator">

    </div>
    <!-- <div role="tabpanel" class="tab-pane fade" id="references">ccc</div> -->
  </div>
  </div>


</div>