config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  devise_for :users, path_names:  { sign_in: "login", sign_out: "logout" },
                     controllers: {
                                    registrations: "user/registrations"
                                  }


  #===============Api Routes================
  require 'api_constraints'

   namespace :api, defaults: { format: :json } do
       # scope per version of api
       scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

         resources :sessions, :only      => [:create, :destroy]
         match '/login'                  => 'sessions#create', :via => [:options, :post]
         post '/logout/:user_id'         => 'sessions#destroy'

         match '/reset_password'         => 'users#reset_password', :via => [:post]
         match '/users/:id'              => 'users#update', :via => [:options, :put, :post]
        #  get '/matches'                  => 'matches#show'

         resources :users, :only         => [:show, :create, :update]

         resources :dealerships, :only   => [:index, :show] do
           resources :sales_reps, :controller => 'sales_reps', :only => [:index, :show]
           resources :service_reps, :controller => 'service_reps', :only => [:index, :show]
         end

         resources :messages

         resources :conversations do
          resources :messages
         end
     end
   end
   #==========================================

  resources :users, only: [:index, :show, :destroy]
  resources :moderators, :controller => 'moderators'
  resources :sales_reps, :controller => 'sales_reps'
  resources :service_reps, :controller => 'service_reps'
  # devise_for :users

  resources :dealerships
  resources :push_notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/push_notification.rb
class PushNotification < ApplicationRecord
  belongs_to :user
  after_create :upload_notification_to_ionic

  validates :message, presence: true
  validates :tokens, presence: true

  # attribute :tokens, :string, array: true
  serialize :tokens, Array

  self.per_page = 10 #Pagination Gem

private
  def upload_notification_to_ionic
    puts self.tokens.to_json


    params = {
      "tokens" => self.tokens,
      "profile" => ENV['IONIC_PUSH_ENV'],
      "notification":{
        "message": self.message,
        "android":{
          "title": "Baker Motor Company"
        },
         "ios": {
              "title": "Baker Motor Company"
            }
      }
    }

    uri = URI.parse('https://api.ionic.io/push/notifications')
    https = Net::HTTP.new(uri.host,uri.port)
    https.use_ssl = true
    req = Net::HTTP::Post.new(uri.path)
    req['Authorization'] = ENV['IONIC_API_TOKEN']
    req['Content-Type'] = 'application/json'
    req.body = params.to_json
    res = https.request(req)
    puts res.body
  end
end

app/controllers/push_notifications_controller.rb
class PushNotificationsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_push_notification, only: [:destroy]

  def index
    # @push_notifications = PushNotification.all
    @push_notifications= PushNotification.all.paginate(:page => params[:page])
  end

  def show
  end

  def new
    @push_notification = PushNotification.new
    @customers = User.where.not('device_token' => nil)
  end

  def edit
  end

  def create
    @push_notification = PushNotification.new(push_notification_params)
    @push_notification.user_id = current_user.id

    respond_to do |format|
      if @push_notification.save
        format.html { redirect_to push_notifications_path, notice: 'Push Notification was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @push_notification.destroy
    respond_to do |format|
      format.html { redirect_to push_notifications_path, notice: 'Push Notification was successfully destroyed.' }
    end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_push_notification
      @push_notification = PushNotification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def push_notification_params
      params.fetch(:push_notification, {}).permit(:message, :sent_to, :user_id, tokens:[])
    end
end

app/views/push_notifications/index.html.erb
<div class="col-lg-10 offset-lg-1">
  <div class="row">
    <h1 class="text-md-center" style="padding: 1rem 0">Push Notifications</h1>
  </div>

  <div class="row">
    <% if current_user.has_role? :admin %>
      <div class="pull-right">
        <%= link_to  new_push_notification_path, :class=>"btn btn-warning"  do %>
          Create Push Notification
          <!-- <i class="fa fa-plus-circle fa-fw" aria-hidden="true"></i> -->
        <% end %>
      </div>
    <% end %>
    <div class="text-lg-left">
      <%= link_to root_path, :class=>"btn btn-danger" do  %>
        <i class="fa fa-chevron-circle-left fa-fw" aria-hidden="true"></i>Back
      <% end %>
    </div>
  </div>

<div class="row" style="padding: 2rem 0">
  <table class="table table-hover" style="background-color: white; padding-top:5rem; border-left: 1px solid #ddd; border-right: 1px solid #ddd; border-bottom: 1px solid #ddd; border-radius: 0rem 0rem .25rem .25rem">
    <thead>
      <tr>
        <th>Message</th>
        <th class="text-lg-center">
          Date Sent
        </th>
        <th class="text-lg-center">
          Actions
        </th>
      </tr>
    </thead>

    <tbody>
      <% if @push_notifications.exists? %>
        <% @push_notifications.each do |notification| %>
          <tr>
            <td><%= notification.message %></td>
            <td class="text-lg-center">
              <%= notification.created_at.strftime("%m/%d/%Y at %I:%M%p") %>
              <!-- <%= link_to 'Destroy', notification, :class=>"btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } if can? :manage, notification %> -->
            </td>
            <td class="text-lg-center">
              <%= link_to 'Remove', notification, :class=>"btn btn-sm btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>

        <% end %>
      <% else %>
        <tr>
          <td colspan="2" class="text-sm-center">
            You Havent Sent Any Push Notifications Yet
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @push_notifications, :renderer => WillPaginate::ActionView::BootstrapLinkRenderer, class: 'pagination-sm text-lg-center' %>

  </div>

</div>

app/views/push_notifications/new.html.erb
<div class="col-lg-10 offset-lg-1">
  <div class="row">
    <h1 class="text-md-center" style="padding: 1rem 0">Create Push Notification</h1>
  </div>

  <%= form_for(@push_notification) do |f| %>
  <div class="row">
    <% if current_user.has_role? :admin %>
      <div class="pull-right" style="width:20%">
        <%= f.submit "Create", :type => "submit", :class=>"btn btn-primary", :style=>"width:100%" %>
      </div>
    <% end %>
    <div class="text-lg-left">
      <%= link_to push_notifications_path, :class=>"btn btn-danger" do  %>
        <i class="fa fa-chevron-circle-left fa-fw" aria-hidden="true"></i>Back
      <% end %>
    </div>
  </div>

  <% if @push_notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@push_notification.errors.count, "error") %> prohibited this push_notification from being saved:</h2>

      <ul>
      <% @push_notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row" style="background-color: white; border-radius:.5em; padding:2em;margin-top: 2.5em;">

  <div class="form-group row">
    <label for="inputName" class="col-sm-2 col-form-label">Message:</label>
    <div class="col-sm-10">
      <%= f.text_field :message, :id=> "inputName", :class=> "form-control", :placeholder=>"Message" %>

    </div>
  </div>

  <div class="form-group row">
    <label for="inputName" class="col-sm-2 col-form-label">Customers:</label>
    <div class="col-sm-10">
    <%= f.collection_check_boxes :tokens, User.where.not('device_token' => nil), :device_token, :email do |b| %>
          <div class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
    <% end %>
          </div>
    </div>
  </div>
</div>
  <% end %>
</div>